include:
- project: stig/inspec-scanning-integration
  ref: 1.1.0
  file: templates/templates.yml

before_script:
  - echo "SCV Pipeline for Apache 2.4 Site"

stages:
  - check
  - lint
  - exec
  - publish

check Apache_2.4_Site:
  extends: .ci:stage:check:inspec

lint Apache_2.4_Site:
  extends: .ci:stage:lint:inspec

exec Apache_2.4_Site:
  extends: .ci:stage:exec:inspec
  variables:
    TARGET: 'rep.dsolab.io/baselines/apache2.4_baseline:1.1'

publish Apache_2.4_Site:
  extends: .ci:stage:publish:inspec
  dependencies:
  - exec Apache_2.4_Site
